apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incidentflow-k8s-agent.fullname" . }}
  labels:
    {{- include "incidentflow-k8s-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration-token: {{ .Values.registrationToken | quote }}
  agent-token: {{ .Values.agentToken | quote }}
