apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incidentflow-k8s-agent.secretName" . }}
  labels:
    {{- include "incidentflow-k8s-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration-token: {{ .Values.agent.registrationToken | quote }}
  agent-token: {{ .Values.agent.agentToken | default "" | quote }}
