apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "incidentflow-k8s-agent.fullname" . }}
  labels:
    {{- include "incidentflow-k8s-agent.labels" . | nindent 4 }}
automountServiceAccountToken: true
